### PR TITLE
mfrc522 - Fix 4-byte tag UIDs

### LINKED ISSUE #21: MFRC522 - ReadUID() returns 5 bytes for a tag with a 4-byte UID
**Describe the bug**
When reading the UID of a tag with a 4-byte UID `ReadUID()` returns 5 bytes.

**To Reproduce**
1. Call `ReadUID()` and scan an NFC tag with a 4-byte UID.
2. 5 bytes will be returned. Comparing to the tag's known UID, the fifth byte appears to be extraneous.

**Expected behavior**
4 bytes should be returned.

**Platform (please complete the following information):**
 - OS: Raspbian 10.9
 - Board: Gen 1 Raspberry Pi Model B
 - Device: MFRC522

**Additional context**
The problem appears to be here: https://github.com/periph/devices/blob/47f3fec45df8376070823f45f7624567267335a8/mfrc522/mfrc522.go#L404-414

Both `antiColl()` and `antColll2()` check the crc byte but then also return it. In the case of a 4-byte UID `selectCard()` then returns the whole slice including the CRC, oops.

I think in the case of a 7-byte NUID it will also be wrong, the code correctly strips byte 0 (`0x88`), then leaves the crc from `antiColl()`, then strips the crc from `antiColl2()`, meaning it will return 8-bytes but byte 4 will be extraneous.

### PR DESCRIPTION
**Pull request by brackendawson**
4-byte UIDs incorrectly included a 5th csum byte. 7-byte UIDs were unaffected.

fixes #21

### CODE REVIEW

File: mfrc522/mfrc522.go [hunk 1]
```diff
@@ -40,10 +41,22 @@ type config struct {
 	defaultTimeout time.Duration
 	beforeCall     func()
 	afterCall      func()
+	bogusUID       bool
 }
 
 type configF func(*config) *config
 
+// WithFixedUID sets the card reader to return correct 4-byte UIDs. Without
```
Comment (maruel) [inline mfrc522/mfrc522.go:49]: After thinking more, I think it's better to switch the default and have the user explicitly opt in.

File: mfrc522/mfrc522.go [hunk 2]
```diff
@@ -66,15 +79,20 @@ func WithSync() configF {
 func noop() {}
 
 // NewSPI creates and initializes the RFID card reader attached to SPI.
+// It is recommended to use the WithFixedUID configuration to return correct
```
Comment (maruel) [inline mfrc522/mfrc522.go:82]: Then you can skip this comment.

File: mfrc522/mfrc522.go (hunk 1 above)
Comment (brackendawson) [reply mfrc522/mfrc522.go:49]: I'm happy with that, it also means we wouldn't need to update either periph/cmd or periph/website to include the option in the examples.

**Comment by brackendawson** [comment]
Sorry about the force push, it turns out accidentally transposing two characters in my last commit message makes it massively inappropriate. 😳

**Review by maruel — APPROVED** [review]
lgtm albeit I'm a bit concerned that no unit test was touched. I'd be super happy if you can add one as a follow up but won't block on that.

**Comment by maruel** [comment]
No worry about the force push, I squash anyway.
